### PR TITLE
Nodes editable

### PR DESCRIPTION
**Pull request by zzimbler**
This PR should fix that issue that I brought up earlier. Not sure if this is the greatest way to do it, but it gets the job done.

I'm looking at using this in angularjs so I'm not sure if it ever crossed your mind, but it would eventually be great to wrap this into a directive or something that plays very nicely with any angular app.
- Zach

### CODE REVIEW

**Comment by zzimbler** [comment]
I lied, I didn't check everything before requesting a pull. The current branch in the PR breaks adding links... Looking into it.

**Comment by zzimbler** [comment]
Okay I think this should be resolved now

**Comment by mduvall** [comment]
Great! Going to take a look at this tonight. Thanks a lot for the fix :+1:

**Comment by mduvall** [comment]
Sorry had to revert this commit, `document.activeElement` is the `body` in Safari and wasn't sure a clean way to implement that. Feel free to re-open this PR if you can find a solution - thanks!

**Comment by zzimbler** [comment]
Hmm that's strange. The spec on MDN is unclear then... I'll find another way to get this to work and re-open the PR.

—
Zachary A. Zimbler

**Comment by zzimbler** [comment]
so I just tested in safari and it seems to be working just fine. That being
said it isn't supported on safari before version 4. I have 7.0 on Mavrick

On Fri, Nov 1, 2013 at 9:46 AM, Zachary Zimbler zachzimbler@gmail.comwrote:

> Hmm that's strange. The spec on MDN is unclear then... I'll find another
> way to get this to work and re-open the PR.
> —
> Zachary A. Zimbler
> Sent from my iPhone
> 
> On Fri, Nov 1, 2013 at 2:39 AM, Matt DuVall notifications@github.comwrote:
> 
> > Sorry had to revert this commit, document.activeElement is the body in
> > Safari and wasn't sure a clean way to implement that. Feel free to re-open
> > this PR if you can find a solution - thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/mduvall/grande.js/pull/50#issuecomment-27550032
> > .

## 

Zachary A. Zimbler
+1(814) 441-2968

**Pull request merged**
